import Foundation

protocol DeveloperDataRuleRegistering: Sendable {
    func allRules() -> [DeveloperDataRule]
}

struct DeveloperDataRuleRegistry: DeveloperDataRuleRegistering {
    
    func allRules() -> [DeveloperDataRule] {
        return [
            // 1. Xcode Derived Data (High confidence, selectable by default)
            DeveloperDataRule(
                id: "xcode.derivedData",
                name: "Xcode Derived Data",
                type: .xcodeDerivedData,
                relativePaths: ["Library/Developer/Xcode/DerivedData"],
                confidence: .high,
                isRegenerable: true,
                isSelectableByDefault: true,
                isProtected: false,
                description: "Build products, indexes, and intermediate data generated by Xcode.",
                consequence: "Projects will regenerate this data when rebuilt. Initial build times may be slightly longer."
            ),
            
            // 2. Xcode Archives (Low confidence, informational only, protected)
            DeveloperDataRule(
                id: "xcode.archives",
                name: "Xcode Archives",
                type: .xcodeArchives,
                relativePaths: ["Library/Developer/Xcode/Archives"],
                confidence: .low,
                isRegenerable: false,
                isSelectableByDefault: false,
                isProtected: true,
                description: "Archived application builds created by Xcode for distribution, debugging, or App Store workflows.",
                consequence: "Archives cannot be automatically regenerated. Review manually in Xcode Organizer."
            ),
            
            // 3. npm Cache (High confidence, selectable by default)
            DeveloperDataRule(
                id: "npm.cache",
                name: "npm Cache",
                type: .npmCache,
                relativePaths: [".npm/_cacache", ".npm"],
                confidence: .high,
                isRegenerable: true,
                isSelectableByDefault: true,
                isProtected: false,
                description: "Cached package tarballs and metadata used by npm.",
                consequence: "npm will re-download cached packages upon next install."
            ),
            
            // 4. Gradle Cache (High confidence, selectable by default)
            DeveloperDataRule(
                id: "gradle.cache",
                name: "Gradle Cache",
                type: .gradleCache,
                relativePaths: [".gradle/caches"],
                confidence: .high,
                isRegenerable: true,
                isSelectableByDefault: true,
                isProtected: false,
                description: "Cached dependencies and build artifacts downloaded or generated by Gradle.",
                consequence: "Gradle will download dependencies anew on next build. (Configuration files remain untouched)."
            ),
            
            // 5. Maven Local Repository (Medium confidence, review manually, NOT default selected)
            DeveloperDataRule(
                id: "maven.repository",
                name: "Maven Local Repository",
                type: .mavenRepository,
                relativePaths: [".m2/repository"],
                confidence: .medium,
                isRegenerable: true,
                isSelectableByDefault: false,
                isProtected: false,
                description: "Downloaded Java/Kotlin artifact dependencies in ~/.m2/repository.",
                consequence: "Maven will re-download required packages from remote repositories. (settings.xml remains untouched)."
            ),
            
            // 6. CocoaPods Cache (High confidence, selectable by default)
            DeveloperDataRule(
                id: "cocoapods.cache",
                name: "CocoaPods Cache",
                type: .cocoapodsCache,
                relativePaths: ["Library/Caches/CocoaPods"],
                confidence: .high,
                isRegenerable: true,
                isSelectableByDefault: true,
                isProtected: false,
                description: "Global downloaded pod repositories and release tarballs.",
                consequence: "CocoaPods will fetch pod assets from remote repos on next pod install."
            ),
            
            // 7. Homebrew Cache (High confidence, selectable by default)
            DeveloperDataRule(
                id: "homebrew.cache",
                name: "Homebrew Cache",
                type: .homebrewCache,
                relativePaths: ["Library/Caches/Homebrew"],
                confidence: .high,
                isRegenerable: true,
                isSelectableByDefault: true,
                isProtected: false,
                description: "Downloaded bottle installers, git checkouts, and formula archives.",
                consequence: "Homebrew will re-download bottles if a formula is reinstalled."
            ),
            
            // 8. Yarn Cache (High confidence, selectable by default)
            DeveloperDataRule(
                id: "yarn.cache",
                name: "Yarn Cache",
                type: .yarnCache,
                relativePaths: ["Library/Caches/Yarn", ".yarn/berry/cache"],
                confidence: .high,
                isRegenerable: true,
                isSelectableByDefault: true,
                isProtected: false,
                description: "Cached package tarballs downloaded by Yarn.",
                consequence: "Yarn will re-download packages on next yarn install."
            ),
            
            // 9. pnpm Store (High confidence, selectable by default)
            DeveloperDataRule(
                id: "pnpm.store",
                name: "pnpm Store",
                type: .pnpmStore,
                relativePaths: [".pnpm-store", "Library/pnpm/store"],
                confidence: .high,
                isRegenerable: true,
                isSelectableByDefault: true,
                isProtected: false,
                description: "Global content-addressable package storage shared across projects.",
                consequence: "pnpm will recreate store entries as needed."
            ),
            
            // 10. Android Studio Cache (Medium confidence, review manually)
            DeveloperDataRule(
                id: "androidstudio.cache",
                name: "Android Studio Cache",
                type: .androidBuildCache,
                relativePaths: ["Library/Caches/Google", ".android/build-cache"],
                confidence: .medium,
                isRegenerable: true,
                isSelectableByDefault: false,
                isProtected: false,
                description: "Intermediate indexing and build caches from Android Studio.",
                consequence: "Android Studio will rebuild indexing data when opening projects."
            ),
            
            // 11. Docker Data (Low confidence, informational only, protected)
            DeveloperDataRule(
                id: "docker.data",
                name: "Docker Data",
                type: .dockerCache,
                relativePaths: ["Library/Containers/com.docker.docker"],
                confidence: .low,
                isRegenerable: false,
                isSelectableByDefault: false,
                isProtected: true,
                description: "Container runtime disks, images, volumes, and state used by Docker Desktop.",
                consequence: "SweepMyMac does not remove Docker runtime data automatically. Manage via Docker Desktop."
            ),
            
            // 12. Colima Data (Low confidence, informational only, protected)
            DeveloperDataRule(
                id: "colima.data",
                name: "Colima Data",
                type: .colimaData,
                relativePaths: [".colima"],
                confidence: .low,
                isRegenerable: false,
                isSelectableByDefault: false,
                isProtected: true,
                description: "Virtual machine disks and container runtime data managed by Colima.",
                consequence: "SweepMyMac will not remove Colima runtime data. Use `colima delete` if desired."
            )
        ]
    }
}
